package lk.slpa.mpma.backend.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import java.util.Date;

/**
 * Entity class representing course material in the MPMA system.
 *
 * <p>This class serves as the base entity for different types of learning materials that can be
 * associated with courses. It uses inheritance to allow specialized material types (documents,
 * announcements, etc.) while maintaining common attributes. The class uses joined inheritance
 * strategy for efficient database storage.
 */
@Entity
@Table(name = "material")
@Inheritance(strategy = InheritanceType.JOINED)
@lombok.Data
public class Material {
  /** Unique identifier for the material. Auto-generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "material_id", nullable = false)
  private Long materialId;

  /** Title or name of the material. Used for display and identification purposes. */
  @Column(nullable = false)
  private String title;

  /** Date when the material was uploaded to the system. */
  @Column(nullable = false)
  private Date uploadDate;

  /**
   * Flag indicating whether the material is visible to students. Allows lecturers to prepare
   * materials before making them available.
   */
  @Column(nullable = false)
  private Boolean visible;

  /** Detailed description of the material. */
  @Column(nullable = false)
  private String description;

  /**
   * Reference to the course that this material belongs to. JsonBackReference prevents infinite
   * recursion in JSON serialization.
   */
  @JsonBackReference
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "course_id", nullable = false)
  private Course course;

  /** Reference to the person (typically a lecturer) who created this material. */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "person_id", nullable = false)
  private Person creator;

  /**
   * Type of the material, represented by the MaterialType enum. Stored as a string in the database.
   */
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private MaterialType type;

  /**
   * Enum defining possible types of course materials. Each type corresponds to a specific subclass
   * of Material.
   */
  public enum MaterialType {
    /** Document-based materials like PDFs, presentations, etc. */
    DOCUMENT,

    /** Announcements to convey important information to students */
    ANNOUNCEMENT,

    /** External resources linked from other websites */
    LINKED,

    /** Interactive learning activities */
    ACTIVITY
  }
}
