package lk.slpa.mpma.backend.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Entity class representing an option in multiple-choice or single-choice questions.
 *
 * <p>This entity stores individual answer options that can be associated with questions that have
 * predefined answer choices. Each option has text content and can be referenced as a correct answer
 * from the parent question.
 */
@Entity
@Table(name = "question_option")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class QuestionOption {

  /** Unique identifier for the option. Auto-generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** Reference to the parent question that this option belongs to. */
  @ManyToOne
  @JoinColumn(name = "question_id", nullable = false)
  @EqualsAndHashCode.Exclude // Prevent recursion
  @ToString.Exclude // Prevent recursion
  private Question question;

  /** The text content of this answer option. */
  @Column(name = "option_text", nullable = false, columnDefinition = "TEXT")
  private String optionText;

  /** Optional ordering position of this option within the question's option list. */
  @Column private Integer position;
}
