package com.LmsProject.AdminInterface.Model;

import jakarta.persistence.*;
import java.util.Date;
import lombok.Data;

/**
 * Base entity class representing a person in the MPMA system.
 *
 * <p>This is the parent class for various user types (Administrator, Lecturer, Student, etc.) using
 * inheritance mapping. It contains common attributes shared by all user types. The class uses
 * joined inheritance strategy to create separate tables for each subclass.
 */
@Entity
@Table(name = "person")
@Inheritance(strategy = InheritanceType.JOINED)
@Data
public class Person {

  /** Unique identifier for a person. Auto-generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "person_id", nullable = false) // Changed to match DB column name
  private Long personId;

  /** Full name of the person. */
  @Column(nullable = false)
  private String name;

  /** Username for authentication. Must be unique across all users. */
  @Column(unique = true, nullable = false)
  private String username;

  /** Encrypted password for authentication. */
  @Column(nullable = false)
  private String password;

  /** Role of the user in the system. Mapped to UserRole enum. */
  @Enumerated(EnumType.STRING)
  @Column(name = "role", nullable = false)
  private UserRole userRole;

  /** Physical address of the person. Optional field. */
  @Column private String address;

  /** Date of birth of the person. Stored as DATE type in database. */
  @Temporal(TemporalType.DATE)
  @Column(name = "date_of_birth") // Changed to match DB column name
  private Date dateOfBirth;

  /** Represents the gender of the person. */
  @Column(name = "gender", length = 8)
  private String gender;

  /** Contact phone number of the person. Optional field. */
  @Column(name = "phone_number") // Changed to match DB column name
  private String phoneNumber;

  /** Email address of the person. Optional field but typically used for communications. */
  @Column private String email;

  /** Path or URL to the user's profile picture. Optional field. */
  @Column(name = "profile_picture") // Changed to match DB column name
  private String profilePicture;

  /**
   * Enum defining possible user roles in the system. This enum is stored as a string in the
   * database.
   */
  public enum UserRole {
    ADMINISTRATOR,
    LECTURER,
    STUDENT,
    TRAINER,
    TRAINEE
  }
}
